version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "90:90"
      - "444:444"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/nginx/conf.d
      - /var/log/nginx
    env_file:
      - .env
  nest:
    build:
      context: .
      dockerfile: Dockerfile-nest
    ports:
      - "9090:9090"
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}

volumes:
  mariadb_data: