version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "88:88"
      - "444:444"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/nginx/conf.d
      - /var/log/nginx
    env_file:
      - .env
  api:
    build:
      context: .
      dockerfile: Dockerfile-nest
    ports:
      - "8888:8888"
    restart: on-failure
    env_file:
      - .env

volumes:
  mariadb_data: