version: '3'

services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: kawa_db
      MARIADB_USER: kawa
      MARIADB_PASSWORD: root
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    build:
      context: .
      dockerfile: Dockerfile-mariadb
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/nginx/conf.d
      - /var/log/nginx
  api:
    build:
      context: .
      dockerfile: Dockerfile-nest
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    restart: on-failure
volumes:
  mariadb_data:
